#!/usr/bin/env bash
set -e

# Find the repository root so the script works regardless of the current directory.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

JOB_NAME="journal-api-database-setup"
CONFIG_MAP_NAME="journal-api-database-schema"

cleanup() {
    kubectl --namespace default delete \
        "job/${JOB_NAME}" \
        "secret/${JOB_NAME}" \
        "configmap/${CONFIG_MAP_NAME}" \
        --ignore-not-found >/dev/null 2>&1 || true
}

# Read the infrastructure addresses and names saved in the Terraform state.
AWS_REGION="$(terraform -chdir="${REPO_ROOT}/infra" output -raw aws_region)"
CLUSTER_NAME="$(terraform -chdir="${REPO_ROOT}/infra" output -raw eks_cluster_name)"
PGHOST="$(terraform -chdir="${REPO_ROOT}/infra" output -raw rds_address)"
PGDATABASE="$(terraform -chdir="${REPO_ROOT}/infra" output -raw rds_database_name)"
SECRET_ARN="$(terraform -chdir="${REPO_ROOT}/infra" output -raw rds_master_user_secret_arn)"

# Add the EKS cluster to kubeconfig so kubectl knows which cluster to use.
aws eks update-kubeconfig --region "${AWS_REGION}" --name "${CLUSTER_NAME}" >/dev/null

# Retrieve the RDS master username and password generated by AWS.
SECRET_JSON="$(
    aws secretsmanager get-secret-value \
        --region "${AWS_REGION}" \
        --secret-id "${SECRET_ARN}" \
        --query SecretString \
        --output text
)"
# Extract the username and password from the JSON returned by AWS Secrets Manager.
PGUSER="$(printf '%s' "${SECRET_JSON}" | python -c 'import json,sys; print(json.load(sys.stdin)["username"])')"
PGPASSWORD="$(printf '%s' "${SECRET_JSON}" | python -c 'import json,sys; print(json.load(sys.stdin)["password"])')"

# Clean up an interrupted previous run
cleanup
# Clean up any resources created by this script when it exits
# (this is not triggered immediately, only registered for the EXIT signal).
trap cleanup EXIT

# Temporarily copy the RDS connection settings into Kubernetes. The Job loads
# these keys as the standard environment variables.
kubectl --namespace default create secret generic "${JOB_NAME}" \
    --from-literal=PGHOST="${PGHOST}" \
    --from-literal=PGPORT=5432 \
    --from-literal=PGDATABASE="${PGDATABASE}" \
    --from-literal=PGUSER="${PGUSER}" \
    --from-literal=PGPASSWORD="${PGPASSWORD}" >/dev/null

# Put database_setup.sql in a ConfigMap so Kubernetes can mount it in the Pod.
kubectl --namespace default create configmap "${CONFIG_MAP_NAME}" \
    --from-file="database_setup.sql=${REPO_ROOT}/database_setup.sql" >/dev/null

# Create the Job from the YAML manifest.
kubectl --namespace default apply \
    --filename "${REPO_ROOT}/k8s/database-setup-job.yaml" >/dev/null

# Wait up to 360s for the Kubernetes Job to complete.
# Print its logs on failure before cleanup.
if ! kubectl --namespace default wait \
    --for=condition=complete "job/${JOB_NAME}" --timeout=360s; then
    kubectl --namespace default logs "job/${JOB_NAME}" || true
    exit 1
fi

# Print the successful Kubernetes Job output.
kubectl --namespace default logs "job/${JOB_NAME}"
